# Generated by Django 5.0.7 on 2024-07-30 07:33

import django.db.models.deletion
import hipmessageservice.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='删除标记', default=1, verbose_name='删除标记')),
                ('gmt_updated', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='最后更新时间')),
                ('firm_id', models.CharField(db_comment='唯一标识', default=hipmessageservice.models.id_default, editable=False, max_length=7, unique=True, verbose_name='厂商唯一标识')),
                ('firm_name', models.CharField(db_comment='厂商名称', max_length=64, unique=True, verbose_name='厂商名称')),
                ('firm_name_en', models.CharField(blank=True, db_comment='厂商英文名称', max_length=64, null=True, verbose_name='厂商英文名称')),
                ('firm_name_short', models.CharField(blank=True, db_comment='厂商名称简称', max_length=64, null=True, verbose_name='厂商名称简称')),
                ('api_url', models.URLField(blank=True, db_comment='api地址', null=True, verbose_name='api地址')),
                ('creator', models.ForeignKey(db_comment='创建人', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_creator', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updater', models.ForeignKey(db_comment='修改者', db_constraint=1, default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_updater', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '厂商信息',
                'verbose_name_plural': '厂商信息',
            },
        ),
        migrations.CreateModel(
            name='CDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='删除标记', default=1, verbose_name='删除标记')),
                ('gmt_updated', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='最后更新时间')),
                ('value', models.CharField(db_comment='文档代码', max_length=5, unique=True, verbose_name='文档代码')),
                ('comment', models.CharField(db_comment='文档名称', max_length=20, verbose_name='文档名称')),
                ('notes', models.TextField(blank=True, db_comment='备注说明', null=True, verbose_name='备注说明')),
                ('creator', models.ForeignKey(db_comment='创建人', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_creator', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updater', models.ForeignKey(db_comment='修改者', db_constraint=1, default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_updater', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
                ('firm', models.ManyToManyField(db_constraint=1, related_name='系统', to='hipmessageservice.firm', verbose_name='系统')),
            ],
            options={
                'verbose_name': 'CDA文档',
                'verbose_name_plural': 'CDA文档',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='删除标记', default=1, verbose_name='删除标记')),
                ('gmt_updated', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='最后更新时间')),
                ('application_id', models.CharField(db_comment='系统唯一标识', default=hipmessageservice.models.id_default, editable=False, max_length=7, unique=True, verbose_name='系统唯一标识')),
                ('application_code', models.CharField(blank=True, db_comment='系统代码', max_length=32, null=True, verbose_name='系统代码')),
                ('application_name', models.CharField(db_comment='系统名称', max_length=32, unique=True, verbose_name='系统名称')),
                ('application_category', models.CharField(blank=True, db_comment='系统分类', max_length=32, null=True, verbose_name='系统分类')),
                ('description', models.CharField(blank=True, db_comment='系统描述', max_length=32, null=True, verbose_name='系统描述')),
                ('is_customer', models.BooleanField(db_comment='是否为国家标准外', db_default=False, default=True, verbose_name='是否为国家标准外')),
                ('creator', models.ForeignKey(db_comment='创建人', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_creator', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updater', models.ForeignKey(db_comment='修改者', db_constraint=1, default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_updater', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
                ('firm', models.ForeignKey(blank=True, db_comment='厂商名称', db_constraint=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='hipmessageservice.firm', verbose_name='厂商名称')),
            ],
            options={
                'verbose_name': '系统名称',
                'verbose_name_plural': '系统名称',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='删除标记', default=1, verbose_name='删除标记')),
                ('gmt_updated', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='最后更新时间')),
                ('service_id', models.UUIDField(db_comment='服务唯一标识', default=uuid.uuid4, unique=True, verbose_name='服务id')),
                ('service_code', models.CharField(db_comment='服务代码', max_length=32, unique=True, verbose_name='服务代码')),
                ('service_name', models.CharField(db_comment='服务名称', max_length=32, verbose_name='服务名称')),
                ('service_category', models.CharField(blank=True, db_comment='服务分类', max_length=32, null=True, verbose_name='服务分类')),
                ('service_description', models.CharField(blank=True, db_comment='服务描述', max_length=128, null=True, verbose_name='服务描述')),
                ('service_queue', models.SmallIntegerField(db_comment='序号', default=1, unique=True, verbose_name='序号')),
                ('service_status', models.BooleanField(db_comment='服务状态', db_default=False, verbose_name='服务完成状态')),
                ('service_rank', models.CharField(blank=True, db_comment='服务等级', max_length=8, null=True, verbose_name='服务等级')),
                ('is_v3', models.BooleanField(db_comment='是否是国家标准', db_default=False, verbose_name='是否是国家标准')),
                ('is_lookup', models.BooleanField(blank=True, db_comment='是否为查询类接口', db_default=False, default=False, null=True, verbose_name='是否为查询类接口')),
                ('creator', models.ForeignKey(db_comment='创建人', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_creator', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updater', models.ForeignKey(db_comment='修改者', db_constraint=1, default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_updater', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务',
            },
        ),
        migrations.CreateModel(
            name='StatusShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='删除标记', default=1, verbose_name='删除标记')),
                ('gmt_updated', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='最后更新时间')),
                ('status', models.SmallIntegerField(choices=[(1, '订阅'), (2, '发布'), (3, '全部')], db_comment='发布订阅状态', default=2, verbose_name='发布订阅状态')),
                ('is_online', models.BooleanField(db_comment='上线状态', db_default=False, default=False, verbose_name='上线状态')),
                ('application', models.ForeignKey(db_comment='系统', db_constraint=1, on_delete=django.db.models.deletion.PROTECT, to='hipmessageservice.application', verbose_name='系统')),
                ('creator', models.ForeignKey(db_comment='创建人', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_creator', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('service', models.ForeignKey(db_comment='服务', db_constraint=1, on_delete=django.db.models.deletion.PROTECT, to='hipmessageservice.service', verbose_name='服务')),
                ('updater', models.ForeignKey(db_comment='修改者', db_constraint=1, default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_updater', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '发布订阅关系',
                'verbose_name_plural': '发布订阅关系',
                'unique_together': {('application', 'service')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='applications',
            field=models.ManyToManyField(related_name='系统', through='hipmessageservice.StatusShip', to='hipmessageservice.application', verbose_name='系统'),
        ),
    ]
