# Generated by Django 5.0 on 2024-02-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipmessageservice', '0002_firm_application_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapplicationstatus',
            name='is_online',
            field=models.BooleanField(db_comment='上线状态', db_default=models.Value(False), default=False, verbose_name='上线状态'),
        ),
    ]
