# Generated by Django 5.0 on 2024-02-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipmessageservice', '0003_serviceapplicationstatus_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_customer',
            field=models.BooleanField(db_comment='是否为国家标准外', db_default=models.Value(False), default=True, verbose_name='是否为国家标准外'),
        ),
    ]
