# Generated by Django 5.0 on 2024-03-06 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipmessageservice', '0005_alter_application_application_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='删除标记', default=False, verbose_name='删除标记')),
                ('gmt_updated', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='最后更新时间')),
                ('status', models.SmallIntegerField(choices=[(1, '订阅'), (2, '发布'), (3, '全部')], db_comment='发布订阅状态', default=2, verbose_name='发布订阅状态')),
                ('is_online', models.BooleanField(db_comment='上线状态', db_default=models.Value(False), default=False, verbose_name='上线状态')),
                ('application', models.ForeignKey(db_comment='系统', on_delete=django.db.models.deletion.PROTECT, to='hipmessageservice.application', verbose_name='系统')),
                ('creator', models.ForeignKey(db_comment='创建人', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_creator', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('service', models.ForeignKey(db_comment='服务', on_delete=django.db.models.deletion.PROTECT, to='hipmessageservice.service', verbose_name='服务')),
                ('updater', models.ForeignKey(db_comment='修改者', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_updater', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '发布订阅关系',
                'verbose_name_plural': '发布订阅关系',
                'unique_together': {('application', 'service')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='applications',
            field=models.ManyToManyField(blank=True, null=True, related_name='系统', through='hipmessageservice.StatusShip', to='hipmessageservice.application', verbose_name='系统'),
        ),
        migrations.DeleteModel(
            name='ServiceApplicationStatus',
        ),
    ]
