# Generated by Django 5.0 on 2024-03-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipmessageservice', '0006_statusship_service_applications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='firm_name_short',
            field=models.CharField(blank=True, db_comment='厂商名称简称', max_length=64, null=True, verbose_name='厂商名称简称'),
        ),
    ]
