# Generated by Django 5.0 on 2024-03-08 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipmessageservice', '0007_firm_firm_name_short'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='删除标记', default=False, verbose_name='删除标记')),
                ('gmt_updated', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='最后更新时间')),
                ('value', models.CharField(db_comment='文档代码', max_length=5, verbose_name='文档代码')),
                ('comment', models.CharField(db_comment='文档名称', max_length=20, verbose_name='文档名称')),
                ('creator', models.ForeignKey(db_comment='创建人', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_creator', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('firm', models.ManyToManyField(blank=True, null=True, related_name='系统', to='hipmessageservice.firm', verbose_name='系统')),
                ('updater', models.ForeignKey(db_comment='修改者', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_updater', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': 'CDA文档',
                'verbose_name_plural': 'CDA文档',
            },
        ),
    ]
