# Generated by Django 5.0 on 2024-03-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipmessageservice', '0008_cda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cda',
            name='notes',
            field=models.TextField(blank=True, db_comment='备注说明', null=True, verbose_name='备注说明'),
        ),
    ]
