# Generated by Django 5.0.3 on 2024-03-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipmessageservice', '0010_alter_cda_firm_alter_cda_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_customer',
            field=models.BooleanField(db_comment='是否为国家标准外', db_default=False, default=True, verbose_name='是否为国家标准外'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_lookup',
            field=models.BooleanField(blank=True, db_comment='是否为查询类接口', db_default=False, default=False, null=True, verbose_name='是否为查询类接口'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_v3',
            field=models.BooleanField(db_comment='是否是国家标准', db_default=False, verbose_name='是否是国家标准'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_status',
            field=models.BooleanField(db_comment='服务状态', db_default=False, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='statusship',
            name='is_online',
            field=models.BooleanField(db_comment='上线状态', db_default=False, default=False, verbose_name='上线状态'),
        ),
    ]
