# Generated by Django 5.0.3 on 2024-05-09 08:32

import hipmessageservice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipmessageservice', '0011_alter_application_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.CharField(db_comment='系统唯一标识', default=hipmessageservice.models.id_default, max_length=7, unique=True, verbose_name='系统唯一标识'),
        ),
    ]
