# Generated by Django 5.0.3 on 2024-05-09 08:35

import hipmessageservice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipmessageservice', '0013_alter_application_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='firm_id',
            field=models.CharField(db_comment='唯一标识', default=hipmessageservice.models.id_default, editable=False, max_length=7, unique=True, verbose_name='厂商唯一标识'),
        ),
    ]
