version: '3.7'

services:
  app:
    image: ${APP_IMAGE}
    restart: unless-stopped
#    for beta
#    command: python manage.py runserver 0.0.0.0:8000
#    for producation
#    command: gunicorn django_hip_service.wsgi:application -b 0.0.0.0:8000 --preload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - data_static:/opt/app/static
      - /d/Projects/django_hip_service/hipmessageservice/static/hipmessageservice/services:/opt/app/hipmessageservice/static/hipmessageservice/services

  web:
      image: ${NGINX_APP_IMAGE}
      restart: unless-stopped
      links:
        - chat:app
      ports:
        - "80:80"
        - "443:443"
      env_file:
        - .env
      environment:
        - TZ=Asia/Shanghai
      volumes:
        - ./config/default.conf.template:/etc/nginx/templates/default.conf.template
        - data_nginx_log:/var/log/nginx
        - data_static:/usr/share/nginx/static

volumes:
  data_nginx_log:
    driver: local
  data_static:
    driver: local