version: '3.7'

services:
  app:
    image: ${APP_IMAGE}
    restart: unless-stopped
#    for beta
#    command: python manage.py runserver 0.0.0.0:8000
#    for producation
    command: ${command}
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - data_static:/opt/app/static

#  web:
#      image: nginx:1.21.0
#      restart: unless-stopped
#      links:
#        - chatapp:app
#      ports:
#        - "8000:80"
#      environment:
#        - TZ=Asia/Shanghai
#      volumes:
#        - ./config/default_nginx.conf:/etc/nginx/conf.d/default.conf
#        - data_nginx_log:/var/log/nginx
#        - data_static:/opt/app/static/

volumes:
#  data_nginx_log:
#    driver: local
  data_static:
    driver: local