# Generated by Django 5.0 on 2024-02-28 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='删除标记', default=False, verbose_name='删除标记')),
                ('gmt_updated', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='最后更新时间')),
                ('value', models.CharField(db_comment='数据集英文名称', max_length=64, verbose_name='数据集英文名称')),
                ('comment', models.CharField(db_comment='数据集中文名称', max_length=128, verbose_name='数据集中文名称')),
                ('creator', models.ForeignKey(db_comment='创建人', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_creator', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updater', models.ForeignKey(db_comment='修改者', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_updater', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '数据集主表',
                'verbose_name_plural': '数据集主表',
            },
        ),
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='删除标记', default=False, verbose_name='删除标记')),
                ('gmt_updated', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='最后更新时间')),
                ('hd_code', models.CharField(db_comment='内部数据元标识符', max_length=11, verbose_name='内部数据元标识符')),
                ('de_code', models.CharField(blank=True, db_comment='标准数据元标识符', max_length=14, null=True, verbose_name='标准数据元标识符')),
                ('de_en_code', models.CharField(db_comment='数据元英文名', max_length=32, verbose_name='数据元英文名')),
                ('de_name', models.CharField(db_comment='数据元名称', max_length=32, verbose_name='数据元名称')),
                ('definition', models.CharField(blank=True, db_comment='定义', max_length=128, null=True, verbose_name='定义')),
                ('data_type', models.CharField(choices=[('BY', '二进制'), ('T', '时间型'), ('DT', '日期时间型'), ('D', '日期型'), ('N', '数值型'), ('L', '布尔型'), ('S1', '字符型-值域代码表'), ('S2', '字符型-值域范围'), ('S3', '字符型')], db_comment='数据元值的数据类型', max_length=2, verbose_name='数据元值的数据类型')),
                ('expression', models.CharField(blank=True, db_comment='表示格式', max_length=8, null=True, verbose_name='表示格式')),
                ('allowable_value', models.CharField(blank=True, db_comment='数据元允许值', max_length=32, null=True, verbose_name='数据元允许值')),
                ('length', models.PositiveSmallIntegerField(blank=True, db_comment='长度', null=True, verbose_name='长度')),
                ('value', models.CharField(blank=True, db_comment='默认值', max_length=64, null='', verbose_name='默认值')),
                ('creator', models.ForeignKey(db_comment='创建人', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_creator', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updater', models.ForeignKey(db_comment='修改者', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_updater', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
                ('data_set', models.ForeignKey(db_comment='所属数据集', null=True, on_delete=django.db.models.deletion.PROTECT, to='esb_standard.dataset', verbose_name='所属数据集')),
            ],
            options={
                'verbose_name': '数据集表',
                'verbose_name_plural': '数据集表',
            },
        ),
        migrations.CreateModel(
            name='DictMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='删除标记', default=False, verbose_name='删除标记')),
                ('gmt_updated', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='最后更新时间')),
                ('value', models.CharField(db_comment='值', max_length=64, verbose_name='值')),
                ('comment', models.CharField(db_comment='值含义', max_length=128, verbose_name='值含义')),
                ('creator', models.ForeignKey(db_comment='创建人', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_creator', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updater', models.ForeignKey(db_comment='修改者', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_updater', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '字典主表',
                'verbose_name_plural': '字典主表',
            },
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='删除标记', default=False, verbose_name='删除标记')),
                ('gmt_updated', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='最后更新时间')),
                ('value', models.CharField(db_comment='值', max_length=64, verbose_name='值')),
                ('comment', models.CharField(db_comment='值含义', max_length=128, verbose_name='值含义')),
                ('creator', models.ForeignKey(db_comment='创建人', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_creator', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updater', models.ForeignKey(db_comment='修改者', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_updater', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
                ('value_dict', models.ForeignKey(db_comment='所属字典', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='value_dict', to='esb_standard.dictmain', verbose_name='所属字典')),
            ],
            options={
                'verbose_name': '字典表',
                'verbose_name_plural': '字典表',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='删除标记', default=False, verbose_name='删除标记')),
                ('gmt_updated', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='最后更新时间')),
                ('service_code', models.CharField(db_comment='事件代码', help_text='事件代码', max_length=6, verbose_name='事件代码')),
                ('service_name', models.CharField(db_comment='事件名称', help_text='事件名称', max_length=32, verbose_name='事件名称')),
                ('creator', models.ForeignKey(db_comment='创建人', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_creator', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updater', models.ForeignKey(db_comment='修改者', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_updater', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '消息事件',
                'verbose_name_plural': '消息事件',
            },
        ),
        migrations.CreateModel(
            name='MessageFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='删除标记', default=False, verbose_name='删除标记')),
                ('gmt_updated', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='最后更新时间')),
                ('format', models.JSONField(db_comment='消息格式', help_text='消息格式', verbose_name='消息格式')),
                ('is_custom', models.BooleanField(db_comment='是否未自定义', db_default=models.Value(False), help_text='自定义消息不参与动态构建', verbose_name='是否自定义')),
                ('creator', models.ForeignKey(db_comment='创建人', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_creator', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updater', models.ForeignKey(db_comment='修改者', default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_updater', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
                ('service', models.ForeignKey(db_comment='对应事件', help_text='对应事件', on_delete=django.db.models.deletion.PROTECT, to='esb_standard.service', verbose_name='事件')),
            ],
            options={
                'verbose_name': '消息格式',
                'verbose_name_plural': '消息格式',
            },
        ),
    ]
