# Generated by Django 5.0.3 on 2024-05-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esb_standard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageformat',
            name='is_custom',
            field=models.BooleanField(db_comment='是否未自定义', db_default=False, help_text='自定义消息不参与动态构建', verbose_name='是否自定义'),
        ),
    ]
