# Generated by Django 5.0.3 on 2024-05-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0002_alter_patient_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(db_comment='Patient ID', db_index=True, help_text='Patient ID', max_length=36, unique=True),
        ),
    ]
