name: Docker Image CI

on:
  workflow_run:
    workflows: ["labeler.yml"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的 Git 历史记录，包括标签

      - name: Log in to Docker Hub
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: Build base image
        run: bash scripts/build-base-image.sh

      - name: Build docker image
        run: bash scripts/build-image.sh

      - name: Push Docker image
        run: bash scripts/push-image.sh
